### ISSUE TITLE
Error al instalar en Debian 7

### ISSUE THREAD

**Issue by leogg** [kikeonline/chocolita-npm-installer#1]
Error al instalar en Debian 7. 

```
npm ERR! Failed at the nodegit@0.16.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
```

Versión de node y npm:

```
$ node -v
v7.0.0
$ npm -v
3.10.9
```
[npm-debug.log.zip](https://github.com/kikeonline/chocolita-npm-installer/files/573443/npm-debug.log.zip)

**Comment by leogg** [comment]
Investigando un poco... parece que Linux tiene problemas con `node-gyp`: [nodejs/node-gyp#454](https://github.com/nodejs/node-gyp/issues/454)

Resolví el problema con `sudo npm install --unsafe-perm --verbose -g chocolita-npm-installer`

Previamente tuve que instalar los archivos de cabecera de openssl: `sudo apt-get install libssl-dev`

**Comment by kikeonline** [comment]
ok, lo pondré en documentación. 👍
